### ISSUE TITLE
Write estimated cost of living calculator

### ISSUE THREAD

**Issue by Zachwhip** [EECE3093C/team-project-dylan-backend#10]
FUNCTIONAL. Write a program that fetches data from google to give an estimate of the cost of living given a location.

**Comment by PerryJohnsonUC** [comment]
Moved to next week

**Comment by bsabo17** [comment]
Are we including more than just rent right now? I believe we can successfully fetch rent data from Google (ask Dylan)

**Comment by bsabo17** [comment]
Budget breakdown will need to be modified accordingly

**Comment by bsabo17** [comment]
Not needed
