### ISSUE TITLE
Determine best programming language for backend code

### ISSUE THREAD

**Issue by PerryJohnsonUC** [EECE3093C/team-project-dylan-backend#15]

**Comment by PerryJohnsonUC** [comment]
Flask/Python/HTML seems to be the best way to associate buttons and code on frontend webpage with backend Python code

**Comment by bsabo17** [comment]
Another option is Java Script since it works well with web servers, but the team is more familiar with Python

**Comment by DylanShaffer20** [comment]
Java Script is valid but would be more limited based on our knowledge

**Comment by bsabo17** [comment]
Team agreed that Python/Flask is the best solution given our background
