### ISSUE TITLE
Look into Flask

### ISSUE THREAD

**Issue by Tiiglo** [EECE3093C/team-project-dylan-backend#16]
Perry mentioned using this program to allow us to connect our website directly to our Python code.

**Comment by Tiiglo** [comment]
Flask is used for developing web applications using python, implemented on Werkzeug and Jinja2.
Werkzeug is just a built in library within flask which can be used to create our web application

**Comment by bsabo17** [comment]
Does this create the web interface itself or do we still have to create/host it separately?

**Comment by PerryJohnsonUC** [comment]
Same as issue #5, discussed and closed on meeting 3/29
