### ISSUE TITLE
Team meeting 3/1/23

### ISSUE THREAD

**Issue by bsabo17** [EECE3093C/team-project-dylan-backend#18]
Meet to wrap up Iteration 2 and start Iteration 3

**Comment by PerryJohnsonUC** [comment]
Notes from the meeting:
1. Need to set up web server today or beginning of the next iteration
2. Code is starting to get written for calculators
3. HTML setup needs options for buttons and dropdowns to select different calculators

**Comment by bsabo17** [comment]
Productive meeting, everyone has action items for this weekend
