### ISSUE TITLE
Protect the Main files

### ISSUE THREAD

**Issue by Tiiglo** [EECE3093C/team-project-dylan-backend#29]
Should we create a separate file which allows us to test all of our commits before pushing them to main?
Also, another idea is that we could need others to look over the code before it is able to be committed just to ensure everything works properly before it is added to the main code.

**Comment by bsabo17** [comment]
We should be doing some kind of review before merging someone's dev branch into main if a feature has been added

**Comment by Tiiglo** [comment]
I believe that I have updated it so that all new commits need to be made to a different branch then submitted to the main branch via a pull request. I have also made it so that 2 approvals are needed before the code can be merged into the main branch.
